ROLE_PERMISSION_MAP = {
    "admin": [
        "users.view",
        "users.create",
        "users.edit",
        "users.deactivate",
        "users.reset_password",
        "users.force_logout",
        "roles.view",
        "roles.edit",
        "permissions.view",
        "permissions.manage",
        "specialists.view",
        "specialists.create",
        "specialists.edit",
        "specialists.deactivate",
        "specialists.assign_group",
        "groups.view",
        "groups.create",
        "groups.edit",
        "groups.manage_members",
        "sessions.view_all",
        "audit.view_scope",
        "audit.view_all",
        "audit.export",
        "dashboards.view_admin",
        "dashboards.view_dispatcher",
    ],
    "dispatcher": [
        "specialists.view",
        "specialists.create",
        "specialists.edit",
        "specialists.deactivate",
        "specialists.assign_group",
        "groups.view",
        "groups.create",
        "groups.edit",
        "groups.manage_members",
        "audit.view_scope",
        "dashboards.view_dispatcher",
    ],
    "analyst": [
        "dashboards.view_admin",
    ],
    "specialist": [],
    "viewer": [],
}